name: Build JoyConPlusPlus

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: Compile JoyConPlusPlus
        shell: cmd
        # /link 以降に、必要な部品（.lib）をすべて詰め込みました！
        run: |
          cl.exe /EHsc /O2 /std:c++17 *.cpp /Fe:JoyConPlusPlus.exe /link windowsapp.lib Advapi32.lib User32.lib Ole32.lib Shell32.lib runtimeobject.lib

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: JoyConPlusPlus-Exe
          path: ./*.exe
